name: flutter_shaders_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ^3.7.0-1.2.pre
  sdk: ">=2.18.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - shaders/pixelation.frag
  assets:
    - assets/dash.jpg
